services:
  db:
    image: postgres:16
    container_name: sgiguard-db
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpassword
      POSTGRES_DB: sgiguard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: