spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sgiguard}
spring.datasource.username=${DB_USERNAME:produser}
spring.datasource.password=${DB_PASSWORD:prodpassword}

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false