# H2
spring.datasource.url=jdbc:h2:mem:sgiguard
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop

server.error.include-message=always
server.error.include-stacktrace=never

# make html-files reload directly on change
spring.thymeleaf.cache=false